### ISSUE TITLE
A caixa das perguntas não se adapta a monitores de baixa resolução

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/impact-measurement-wp-plugin#16]
![erro-visualizacao-perguntas-im-tela-baixa-resolucao](https://user-images.githubusercontent.com/1226218/106475804-20e15b80-6485-11eb-83b2-cd74c534784a.png)

Mesmo fazendo o scrolldown da página do site, a caixa das perguntas fica cortada.

Ao reduzir o zoom em 67%, é possível ver a caixa das perguntas completamente

![erro-visualizacao-perguntas-im-tela-baixa-resolucao-67%](https://user-images.githubusercontent.com/1226218/106475934-440c0b00-6485-11eb-8f70-ae7970929d23.png)

**Comment by marcioalvessilva** [comment]
Boa Tarde!

Inserir o código abaixo antes do breakpoint 768px "@media (max-width: 768px){...}"

```
@media(max-height: 992px){
	#boxFeedback{
		top: 30%;
	}
}
@media(max-height: 600px){
	#boxFeedback{
		top: 10%;
	}
}
```

@wilsonmoura - por favor inserir e validar!
Qualquer coisa estou à disposição.

**Comment by wilsonmoura** [comment]
@renatomurasaki Ajustes incorporados. Favor testar.

**Comment by renatomurasaki** [comment]
@marcioalvessilva @wilsonmoura obrigado! Testado e aprovado
