### ISSUE TITLE
IM - pagina produtos e serviços

### ISSUE THREAD

**Issue by Lizbiruel** [bireme/impact-measurement-wp-plugin#17]
Navegador Chrome

1- Portal da BVS Regional - pagina Produtos e Serviços IM - após preencher as questões e clicar em ENVIAR (não faz o envio) 

2- A marcação das estrelas não fixam nestas duas questões - Portal da BVS /pagina Sobre 
Quanto você acredita que o conteúdo da BVS é atualizado?
Você acha confiável o conteúdo recuperado na BVS?

3- Estou usando resolução de tela 80% - se aumentar não da pra ver a opção ENVIAR - normalmente uso 100% e acredito que a maioria use essa resolucao

**Comment by renatomurasaki** [comment]
@Lizbiruel o @wilsonmoura vai checar estas questões. 

Sobre o item 3, poderia verificar novamente para ver se o problema persiste?

**Comment by wilsonmoura** [comment]
@renatomurasaki @Lizbiruel Ajustes realizados. Favor testar.

OBS: Talvez seja necessário limpar o cache da página (Shift+F5)
