### ISSUE TITLE
Por que as páginas do EVID@Easy, exemplo https://bvsalud.org/evideasy/pt/ , não mostra o survey do IM?

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/impact-measurement-wp-plugin#19]

**Comment by marcoslmori** [comment]
Como é uma instalação nova de wordpress não tem instalado esse plugin.. vou providenciar

**Comment by renatomurasaki** [comment]
Veja com o @wilsonmoura para configurar corretamente com o ID do portal regional

**Comment by marcoslmori** [comment]
Por favor, @wilsonmoura   mantém esse código  cc35e4af-7e84-4858-8607-473d81a1d7ba?

**Comment by wilsonmoura** [comment]
@marcoslmori pode usar o mesmo código, mas vale destacar que as perguntas que vão aparecer serão as mesmas que estão sendo exibidas no Portal. @renatomurasaki se o ideal é que as perguntas nesse site sejam diferentes, devemos criar no sistema IM um código dedicado e perguntas específicas para esse subsite.

**Comment by renatomurasaki** [comment]
@wilsonmoura ciente. @marcoslmori pode prosseguir

**Comment by marcoslmori** [comment]
Chamado 8087 do ocomon em espera de atendimento

**Comment by marcoslmori** [comment]
@wilsonmoura , o plugin foi ativado e configurado e se mostra no site público.  Nessa versão tem o campo de link do survey. Qual é o link que se deve colocar nesse campo?

**Comment by renatomurasaki** [comment]
@marcoslmori esse link é apenas quando se deseja oferecer para o usuário uma segunda etapa de respostas a um survey externo. No nosso caso, pode deixar em branco. Obrigado!
