### ISSUE TITLE
Configurar interface iAHx do WHO COVID-19 para integrar o serviço IM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/impact-measurement-wp-plugin#25]
@wilsonmoura favor verificar se configurei corretamente o IM. Segue o que fiz:

1) Cadastrei o web site - https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/
2) Cadastrei os novos 5 tipos de resposta 
#20 
#21 
#22 
#23 
#24 
3) Configurei a ordem de apresentação das perguntas para cada tipo de página do iAHx
4) Cadastrei as perguntas em inglês (por enquanto, os 6 idiomas da interface mostrarão tudo em inglês)
5) Cadastrei um contexto novo chamado Geral, pois algumas perguntas não se encaixam nem em funcionalidade, nem em conteúdo

Assim que configurar e verificar que está funcionando, por favor, faça reply-all do e-mail correspondente que você foi copiado hoje (02/09/2021), cujo subject é "WHO COVID-19 Database - survey questions on usefulness of the database"

**Comment by wilsonmoura** [comment]
@renatomurasaki IM configurado e disponível na interface de pesquisa WHO COVID-19. Favor validar.

**Comment by renatomurasaki** [comment]
validado, inclusive pela equipe da OMS, conforme e-mails trocados
